package com.loanmate.utils

import android.content.Context
import android.graphics.Color as AndroidColor
import android.graphics.Paint
import android.graphics.RectF
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import com.loanmate.data.local.LoanEntity
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Locale

/**
 * Generates a one-shot loan statement PDF.
 * Uses Android's built-in PdfDocument — no external deps.
 *
 * Layout: A4 portrait (595 x 842 pt), 36pt margins.
 * Page 1: header + summary card + first 4 loans.
 * Pages 2..N: continuation loans, 5 per page.
 */
object PdfExporter {

    private const val PAGE_WIDTH = 595
    private const val PAGE_HEIGHT = 842
    private const val MARGIN = 36f
    private const val LOAN_CARD_HEIGHT = 130f

    fun export(
        context: Context,
        loans: List<LoanEntity>,
        outFileName: String = defaultFileName()
    ): File {
        val pdf = PdfDocument()
        val title = Paint().apply {
            color = AndroidColor.parseColor("#1565C0")
            textSize = 22f
            isAntiAlias = true
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        }
        val h2 = Paint().apply {
            color = AndroidColor.parseColor("#212121")
            textSize = 14f
            isAntiAlias = true
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        }
        val body = Paint().apply {
            color = AndroidColor.parseColor("#424242")
            textSize = 11f
            isAntiAlias = true
        }
        val muted = Paint().apply {
            color = AndroidColor.parseColor("#757575")
            textSize = 10f
            isAntiAlias = true
        }
        val accent = Paint().apply {
            color = AndroidColor.parseColor("#2E7D32")
            textSize = 11f
            isAntiAlias = true
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        }
        val cardBorder = Paint().apply {
            color = AndroidColor.parseColor("#E0E0E0")
            style = Paint.Style.STROKE
            strokeWidth = 0.7f
        }

        val dateLabel = SimpleDateFormat("dd MMM yyyy, HH:mm", Locale.getDefault())
            .format(java.util.Date())
        val totalOutstanding = loans.sumOf { it.outstandingAmount }
        val totalMonthlyEmi = loans.filter { it.status == com.loanmate.data.model.LoanStatus.ACTIVE }
            .sumOf { it.monthlyEmi }

        var pageNum = 1
        var page: PdfDocument.Page = pdf.startPage(
            PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNum).create()
        )
        var canvas = page.canvas
        var y = MARGIN + 20f

        // --- Header ---
        canvas.drawText("LoanMate", MARGIN, y, title)
        canvas.drawText("Generated $dateLabel", MARGIN, y + 16f, muted)
        y += 40f

        // --- Summary ---
        canvas.drawText("Summary", MARGIN, y, h2)
        y += 18f
        canvas.drawText("Total loans: ${loans.size}", MARGIN, y, body)
        y += 14f
        canvas.drawText("Total outstanding: ${CurrencyUtils.format(totalOutstanding)}", MARGIN, y, body)
        y += 14f
        canvas.drawText("Total monthly EMI: ${CurrencyUtils.format(totalMonthlyEmi)}", MARGIN, y, body)
        y += 24f

        // --- Loans list ---
        canvas.drawText("Loans", MARGIN, y, h2)
        y += 14f

        for (loan in loans) {
            if (y + LOAN_CARD_HEIGHT > PAGE_HEIGHT - MARGIN) {
                pdf.finishPage(page)
                pageNum += 1
                page = pdf.startPage(
                    PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNum).create()
                )
                canvas = page.canvas
                y = MARGIN
            }
            drawLoanCard(
                canvas = canvas,
                loan = loan,
                top = y,
                bodyPaint = body,
                mutedPaint = muted,
                accentPaint = accent,
                borderPaint = cardBorder,
                h2Paint = h2
            )
            y += LOAN_CARD_HEIGHT + 8f
        }

        // Footer on last page
        canvas.drawText(
            "Generated by LoanMate · Page $pageNum",
            MARGIN, (PAGE_HEIGHT - MARGIN / 2).toFloat(),
            muted
        )

        pdf.finishPage(page)

        val outDir = File(context.getExternalFilesDir(null), "exports").apply { mkdirs() }
        val outFile = File(outDir, outFileName)
        FileOutputStream(outFile).use { pdf.writeTo(it) }
        pdf.close()
        return outFile
    }

    private fun drawLoanCard(
        canvas: android.graphics.Canvas,
        loan: LoanEntity,
        top: Float,
        bodyPaint: Paint,
        mutedPaint: Paint,
        accentPaint: Paint,
        borderPaint: Paint,
        h2Paint: Paint
    ) {
        val left = MARGIN
        val right = PAGE_WIDTH - MARGIN
        canvas.drawRoundRect(
            RectF(left, top, right, top + LOAN_CARD_HEIGHT), 8f, 8f, borderPaint
        )
        var ty = top + 18f
        canvas.drawText("${loan.loanType.emoji} ${loan.loanName}", left + 12f, ty, h2Paint)
        ty += 14f
        canvas.drawText("${loan.bankName} · ${loan.loanType.displayName}", left + 12f, ty, mutedPaint)
        ty += 18f

        val col1 = left + 12f
        val col2 = left + 200f
        val col3 = left + 380f
        canvas.drawText("Principal", col1, ty, mutedPaint)
        canvas.drawText("Outstanding", col2, ty, mutedPaint)
        canvas.drawText("EMI", col3, ty, mutedPaint)
        ty += 14f
        canvas.drawText(CurrencyUtils.format(loan.principalAmount), col1, ty, bodyPaint)
        canvas.drawText(CurrencyUtils.format(loan.outstandingAmount), col2, ty, accentPaint)
        canvas.drawText(CurrencyUtils.format(loan.monthlyEmi), col3, ty, bodyPaint)
        ty += 16f
        canvas.drawText("Rate", col1, ty, mutedPaint)
        canvas.drawText("EMIs paid", col2, ty, mutedPaint)
        canvas.drawText("Status", col3, ty, mutedPaint)
        ty += 14f
        canvas.drawText("${loan.interestRate}% (${loan.interestType.displayName})", col1, ty, bodyPaint)
        canvas.drawText("${loan.completedEmis} / ${loan.totalEmis}", col2, ty, bodyPaint)
        canvas.drawText(loan.status.name, col3, ty, bodyPaint)
    }

    private fun defaultFileName(): String {
        val ts = SimpleDateFormat("yyyy-MM-dd_HHmm", Locale.getDefault())
            .format(java.util.Date())
        return "LoanMate_Report_$ts.pdf"
    }
}
